/* generated by vole_mult_tables.py: 128s
 *
 * Bilinear VOLE-multiplication tables; see the companion
 * tables_128s.json for the full bilinear identity and
 * semantics.  Definitions live in the companion .c file.
 *
 * Encoding: each table row is an F_2 bit-vector packed
 * little-endian into uint64 words -- bit i sits in word i/64
 * at bit position i%64, and word 0 holds the low bits.
 */
#ifndef FAEST_128S_TABLES_H
#define FAEST_128S_TABLES_H

#include <stdint.h>

#ifndef FAEST_STATIC_ASSERT
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define FAEST_STATIC_ASSERT(c, m) _Static_assert(c, m)
#elif defined(__cplusplus) && __cplusplus >= 201103L
#define FAEST_STATIC_ASSERT(c, m) static_assert(c, m)
#else
#define FAEST_SA_CONCAT_(a, b) a##b
#define FAEST_SA_CONCAT(a, b) FAEST_SA_CONCAT_(a, b)
#define FAEST_STATIC_ASSERT(c, m) \
  typedef char FAEST_SA_CONCAT(faest_static_assert_, __LINE__)[(c) ? 1 : -1]
#endif
#endif

#define FAEST_128S_LAMBDA 128
#define FAEST_128S_NGATES 314
#define FAEST_128S_WGRIND 7
#define FAEST_128S_NDELTA_BITS 121
#define FAEST_128S_NTREE_BITS 121
#define FAEST_128S_TAU 11

#define FAEST_128S_F_WORDS 2
#define FAEST_128S_G_WORDS 2
#define FAEST_128S_W_TREE_WORDS 2
#define FAEST_128S_W_GATE_WORDS 5
#define FAEST_128S_W_CRT_WORDS 2
#define FAEST_128S_M_TREE_WORDS 2

extern const uint64_t FAEST_128S_F[FAEST_128S_NGATES][FAEST_128S_F_WORDS];
extern const uint64_t FAEST_128S_G[FAEST_128S_NGATES][FAEST_128S_G_WORDS];
extern const uint64_t FAEST_128S_W_TREE[FAEST_128S_LAMBDA][FAEST_128S_W_TREE_WORDS];
extern const uint64_t FAEST_128S_W_GATE[FAEST_128S_LAMBDA][FAEST_128S_W_GATE_WORDS];
extern const uint64_t FAEST_128S_W_CRT[FAEST_128S_LAMBDA][FAEST_128S_W_CRT_WORDS];
extern const uint64_t FAEST_128S_TREE_MODULI[FAEST_128S_TAU];
extern const uint64_t FAEST_128S_M_TREE[FAEST_128S_M_TREE_WORDS];

/* fail to compile if a width macro is inconsistent with the relevant parameter */
FAEST_STATIC_ASSERT(FAEST_128S_NDELTA_BITS == FAEST_128S_LAMBDA - FAEST_128S_WGRIND,
                    "FAEST_128S: NDELTA_BITS must equal LAMBDA - WGRIND");
FAEST_STATIC_ASSERT(FAEST_128S_NTREE_BITS == FAEST_128S_NDELTA_BITS,
                    "FAEST_128S: tree residue width must equal NDELTA_BITS");
FAEST_STATIC_ASSERT(FAEST_128S_F_WORDS == (FAEST_128S_LAMBDA + 63) / 64,
                    "FAEST_128S: F_WORDS desynced from LAMBDA");
FAEST_STATIC_ASSERT(FAEST_128S_G_WORDS == (FAEST_128S_NDELTA_BITS + 63) / 64,
                    "FAEST_128S: G_WORDS desynced from NDELTA_BITS");
FAEST_STATIC_ASSERT(FAEST_128S_W_TREE_WORDS == (FAEST_128S_NTREE_BITS + 63) / 64,
                    "FAEST_128S: W_TREE_WORDS desynced from NTREE_BITS");
FAEST_STATIC_ASSERT(FAEST_128S_W_GATE_WORDS == (FAEST_128S_NGATES + 63) / 64,
                    "FAEST_128S: W_GATE_WORDS desynced from NGATES");
FAEST_STATIC_ASSERT(FAEST_128S_W_CRT_WORDS == (FAEST_128S_NDELTA_BITS + 63) / 64,
                    "FAEST_128S: W_CRT_WORDS desynced from NDELTA_BITS");

#endif /* FAEST_128S_TABLES_H */
