/* generated by vole_mult_tables.py: 192s_em
 *
 * Bilinear VOLE-multiplication tables; see the companion
 * tables_192s_em.json for the full bilinear identity and
 * semantics.  Definitions live in the companion .c file.
 *
 * Encoding: each table row is an F_2 bit-vector packed
 * little-endian into uint64 words -- bit i sits in word i/64
 * at bit position i%64, and word 0 holds the low bits.
 */
#ifndef FAEST_EM_192S_TABLES_H
#define FAEST_EM_192S_TABLES_H

#include <stdint.h>

#ifndef FAEST_STATIC_ASSERT
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define FAEST_STATIC_ASSERT(c, m) _Static_assert(c, m)
#elif defined(__cplusplus) && __cplusplus >= 201103L
#define FAEST_STATIC_ASSERT(c, m) static_assert(c, m)
#else
#define FAEST_SA_CONCAT_(a, b) a##b
#define FAEST_SA_CONCAT(a, b) FAEST_SA_CONCAT_(a, b)
#define FAEST_STATIC_ASSERT(c, m) \
  typedef char FAEST_SA_CONCAT(faest_static_assert_, __LINE__)[(c) ? 1 : -1]
#endif
#endif

#define FAEST_EM_192S_LAMBDA 192
#define FAEST_EM_192S_NGATES 506
#define FAEST_EM_192S_WGRIND 8
#define FAEST_EM_192S_NDELTA_BITS 184
#define FAEST_EM_192S_NTREE_BITS 184
#define FAEST_EM_192S_TAU 16

#define FAEST_EM_192S_F_WORDS 3
#define FAEST_EM_192S_G_WORDS 3
#define FAEST_EM_192S_W_TREE_WORDS 3
#define FAEST_EM_192S_W_GATE_WORDS 8
#define FAEST_EM_192S_W_CRT_WORDS 3
#define FAEST_EM_192S_M_TREE_WORDS 3

extern const uint64_t FAEST_EM_192S_F[FAEST_EM_192S_NGATES][FAEST_EM_192S_F_WORDS];
extern const uint64_t FAEST_EM_192S_G[FAEST_EM_192S_NGATES][FAEST_EM_192S_G_WORDS];
extern const uint64_t FAEST_EM_192S_W_TREE[FAEST_EM_192S_LAMBDA][FAEST_EM_192S_W_TREE_WORDS];
extern const uint64_t FAEST_EM_192S_W_GATE[FAEST_EM_192S_LAMBDA][FAEST_EM_192S_W_GATE_WORDS];
extern const uint64_t FAEST_EM_192S_W_CRT[FAEST_EM_192S_LAMBDA][FAEST_EM_192S_W_CRT_WORDS];
extern const uint64_t FAEST_EM_192S_TREE_MODULI[FAEST_EM_192S_TAU];
extern const uint64_t FAEST_EM_192S_M_TREE[FAEST_EM_192S_M_TREE_WORDS];

/* fail to compile if a width macro is inconsistent with the relevant parameter */
FAEST_STATIC_ASSERT(FAEST_EM_192S_NDELTA_BITS == FAEST_EM_192S_LAMBDA - FAEST_EM_192S_WGRIND,
                    "FAEST_EM_192S: NDELTA_BITS must equal LAMBDA - WGRIND");
FAEST_STATIC_ASSERT(FAEST_EM_192S_NTREE_BITS == FAEST_EM_192S_NDELTA_BITS,
                    "FAEST_EM_192S: tree residue width must equal NDELTA_BITS");
FAEST_STATIC_ASSERT(FAEST_EM_192S_F_WORDS == (FAEST_EM_192S_LAMBDA + 63) / 64,
                    "FAEST_EM_192S: F_WORDS desynced from LAMBDA");
FAEST_STATIC_ASSERT(FAEST_EM_192S_G_WORDS == (FAEST_EM_192S_NDELTA_BITS + 63) / 64,
                    "FAEST_EM_192S: G_WORDS desynced from NDELTA_BITS");
FAEST_STATIC_ASSERT(FAEST_EM_192S_W_TREE_WORDS == (FAEST_EM_192S_NTREE_BITS + 63) / 64,
                    "FAEST_EM_192S: W_TREE_WORDS desynced from NTREE_BITS");
FAEST_STATIC_ASSERT(FAEST_EM_192S_W_GATE_WORDS == (FAEST_EM_192S_NGATES + 63) / 64,
                    "FAEST_EM_192S: W_GATE_WORDS desynced from NGATES");
FAEST_STATIC_ASSERT(FAEST_EM_192S_W_CRT_WORDS == (FAEST_EM_192S_NDELTA_BITS + 63) / 64,
                    "FAEST_EM_192S: W_CRT_WORDS desynced from NDELTA_BITS");

#endif /* FAEST_EM_192S_TABLES_H */
