/* generated by vole_mult_tables.cpp: 128f
 *
 * Bilinear VOLE-multiplication tables.  Definitions live in the
 * companion .c file.
 *
 * Encoding: each table row is an F_2 bit-vector packed
 * little-endian into uint64 words -- bit i sits in word i/64
 * at bit position i%64, and word 0 holds the low bits.
 */
#ifndef FAEST_128F_TABLES_H
#define FAEST_128F_TABLES_H

#include <stdint.h>

#ifndef FAEST_STATIC_ASSERT
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define FAEST_STATIC_ASSERT(c, m) _Static_assert(c, m)
#elif defined(__cplusplus) && __cplusplus >= 201103L
#define FAEST_STATIC_ASSERT(c, m) static_assert(c, m)
#else
#define FAEST_SA_CONCAT_(a, b) a##b
#define FAEST_SA_CONCAT(a, b) FAEST_SA_CONCAT_(a, b)
#define FAEST_STATIC_ASSERT(c, m)                                                                  \
  typedef char FAEST_SA_CONCAT(faest_static_assert_, __LINE__)[(c) ? 1 : -1]
#endif
#endif

#define FAEST_128F_LAMBDA 128
#define FAEST_128F_NGATES 314
#define FAEST_128F_WGRIND 8
#define FAEST_128F_NDELTA_BITS 120
#define FAEST_128F_NTREE_BITS 120
#define FAEST_128F_TAU 16

#define FAEST_128F_F_WORDS 2
#define FAEST_128F_G_WORDS 2
#define FAEST_128F_W_TREE_WORDS 2
#define FAEST_128F_W_GATE_WORDS 5
#define FAEST_128F_W_CRT_WORDS 2
#define FAEST_128F_M_TREE_WORDS 2

extern const uint64_t FAEST_128F_F[FAEST_128F_NGATES][FAEST_128F_F_WORDS];
extern const uint64_t FAEST_128F_G[FAEST_128F_NGATES][FAEST_128F_G_WORDS];
extern const uint64_t FAEST_128F_W_TREE[FAEST_128F_LAMBDA][FAEST_128F_W_TREE_WORDS];
extern const uint64_t FAEST_128F_W_GATE[FAEST_128F_LAMBDA][FAEST_128F_W_GATE_WORDS];
extern const uint64_t FAEST_128F_W_CRT[FAEST_128F_LAMBDA][FAEST_128F_W_CRT_WORDS];
extern const uint64_t FAEST_128F_TREE_MODULI[FAEST_128F_TAU];
extern const uint64_t FAEST_128F_M_TREE[FAEST_128F_M_TREE_WORDS];

/* fail to compile if a width macro is inconsistent with the relevant parameter */
FAEST_STATIC_ASSERT(FAEST_128F_NDELTA_BITS == FAEST_128F_LAMBDA - FAEST_128F_WGRIND,
                    "FAEST_128F: NDELTA_BITS must equal LAMBDA - WGRIND");
FAEST_STATIC_ASSERT(FAEST_128F_NTREE_BITS == FAEST_128F_NDELTA_BITS,
                    "FAEST_128F: tree residue width must equal NDELTA_BITS");
FAEST_STATIC_ASSERT(FAEST_128F_F_WORDS == (FAEST_128F_LAMBDA + 63) / 64,
                    "FAEST_128F: F_WORDS desynced from LAMBDA");
FAEST_STATIC_ASSERT(FAEST_128F_G_WORDS == (FAEST_128F_NDELTA_BITS + 63) / 64,
                    "FAEST_128F: G_WORDS desynced from NDELTA_BITS");
FAEST_STATIC_ASSERT(FAEST_128F_W_TREE_WORDS == (FAEST_128F_NTREE_BITS + 63) / 64,
                    "FAEST_128F: W_TREE_WORDS desynced from NTREE_BITS");
FAEST_STATIC_ASSERT(FAEST_128F_W_GATE_WORDS == (FAEST_128F_NGATES + 63) / 64,
                    "FAEST_128F: W_GATE_WORDS desynced from NGATES");
FAEST_STATIC_ASSERT(FAEST_128F_W_CRT_WORDS == (FAEST_128F_NDELTA_BITS + 63) / 64,
                    "FAEST_128F: W_CRT_WORDS desynced from NDELTA_BITS");

#endif /* FAEST_128F_TABLES_H */
