/* generated by vole_mult_tables.cpp: 256s
 *
 * Bilinear VOLE-multiplication tables.  Definitions live in the
 * companion .c file.
 *
 * Encoding: each table row is an F_2 bit-vector packed
 * little-endian into uint64 words -- bit i sits in word i/64
 * at bit position i%64, and word 0 holds the low bits.
 */
#ifndef FAEST_256S_TABLES_H
#define FAEST_256S_TABLES_H

#include <stdint.h>

#ifndef FAEST_STATIC_ASSERT
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define FAEST_STATIC_ASSERT(c, m) _Static_assert(c, m)
#elif defined(__cplusplus) && __cplusplus >= 201103L
#define FAEST_STATIC_ASSERT(c, m) static_assert(c, m)
#else
#define FAEST_SA_CONCAT_(a, b) a##b
#define FAEST_SA_CONCAT(a, b) FAEST_SA_CONCAT_(a, b)
#define FAEST_STATIC_ASSERT(c, m)                                                                  \
  typedef char FAEST_SA_CONCAT(faest_static_assert_, __LINE__)[(c) ? 1 : -1]
#endif
#endif

#define FAEST_256S_LAMBDA 256
#define FAEST_256S_NGATES 698
#define FAEST_256S_WGRIND 6
#define FAEST_256S_NDELTA_BITS 250
#define FAEST_256S_NTREE_BITS 250
#define FAEST_256S_TAU 22

#define FAEST_256S_F_WORDS 4
#define FAEST_256S_G_WORDS 4
#define FAEST_256S_W_TREE_WORDS 4
#define FAEST_256S_W_GATE_WORDS 11
#define FAEST_256S_W_CRT_WORDS 4
#define FAEST_256S_M_TREE_WORDS 4

extern const uint64_t FAEST_256S_F[FAEST_256S_NGATES][FAEST_256S_F_WORDS];
extern const uint64_t FAEST_256S_G[FAEST_256S_NGATES][FAEST_256S_G_WORDS];
extern const uint64_t FAEST_256S_W_TREE[FAEST_256S_LAMBDA][FAEST_256S_W_TREE_WORDS];
extern const uint64_t FAEST_256S_W_GATE[FAEST_256S_LAMBDA][FAEST_256S_W_GATE_WORDS];
extern const uint64_t FAEST_256S_W_CRT[FAEST_256S_LAMBDA][FAEST_256S_W_CRT_WORDS];
extern const uint64_t FAEST_256S_TREE_MODULI[FAEST_256S_TAU];
extern const uint64_t FAEST_256S_M_TREE[FAEST_256S_M_TREE_WORDS];

/* fail to compile if a width macro is inconsistent with the relevant parameter */
FAEST_STATIC_ASSERT(FAEST_256S_NDELTA_BITS == FAEST_256S_LAMBDA - FAEST_256S_WGRIND,
                    "FAEST_256S: NDELTA_BITS must equal LAMBDA - WGRIND");
FAEST_STATIC_ASSERT(FAEST_256S_NTREE_BITS == FAEST_256S_NDELTA_BITS,
                    "FAEST_256S: tree residue width must equal NDELTA_BITS");
FAEST_STATIC_ASSERT(FAEST_256S_F_WORDS == (FAEST_256S_LAMBDA + 63) / 64,
                    "FAEST_256S: F_WORDS desynced from LAMBDA");
FAEST_STATIC_ASSERT(FAEST_256S_G_WORDS == (FAEST_256S_NDELTA_BITS + 63) / 64,
                    "FAEST_256S: G_WORDS desynced from NDELTA_BITS");
FAEST_STATIC_ASSERT(FAEST_256S_W_TREE_WORDS == (FAEST_256S_NTREE_BITS + 63) / 64,
                    "FAEST_256S: W_TREE_WORDS desynced from NTREE_BITS");
FAEST_STATIC_ASSERT(FAEST_256S_W_GATE_WORDS == (FAEST_256S_NGATES + 63) / 64,
                    "FAEST_256S: W_GATE_WORDS desynced from NGATES");
FAEST_STATIC_ASSERT(FAEST_256S_W_CRT_WORDS == (FAEST_256S_NDELTA_BITS + 63) / 64,
                    "FAEST_256S: W_CRT_WORDS desynced from NDELTA_BITS");

#endif /* FAEST_256S_TABLES_H */
